### ISSUE TITLE
Move split into library

### ISSUE THREAD

**Issue by chimon2000** [johnpryan/trie_router#3]
I have looked at a few different implementations and the split is abstracted away.  Wondering if this should be moved into the library so that it automatically happens on `router.get` and `router.add`?

Other implementations:

https://pkg.go.dev/github.com/ant0ine/go-urlrouter
https://github.com/koajs/trie-router
https://github.com/pillarjs/routington

**Comment by johnpryan** [comment]
Makes sense, `add()` could take a string. The current add() could be renamed to `addPathComponents()` or something similar.

**Comment by chimon2000** [comment]
That makes sense.
